// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EmitProcessInfo(arg1:models.ProcessInfo):Promise<void>;

export function Init():Promise<void>;
