// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CandleStick(arg1, arg2, arg3) {
  return window['go']['api']['App']['CandleStick'](arg1, arg2, arg3);
}

export function CommandMatch(arg1) {
  return window['go']['api']['App']['CommandMatch'](arg1);
}

export function EmitProcessInfo(arg1) {
  return window['go']['api']['App']['EmitProcessInfo'](arg1);
}

export function Init() {
  return window['go']['api']['App']['Init']();
}

export function LogProcessError(arg1) {
  return window['go']['api']['App']['LogProcessError'](arg1);
}

export function LogProcessInfo(arg1) {
  return window['go']['api']['App']['LogProcessInfo'](arg1);
}

export function LogProcessWarn(arg1) {
  return window['go']['api']['App']['LogProcessWarn'](arg1);
}

export function MakeWailsHappy() {
  return window['go']['api']['App']['MakeWailsHappy']();
}

export function StockMeta(arg1) {
  return window['go']['api']['App']['StockMeta'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['api']['App']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['api']['App']['Unsubscribe'](arg1);
}
