// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitProcessInfo(arg1) {
  return window['go']['api']['App']['EmitProcessInfo'](arg1);
}

export function Init() {
  return window['go']['api']['App']['Init']();
}
