// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Connect(arg1:string):Promise<string>;

export function EmitProcessInfo(arg1:api.ProcessInfo):Promise<void>;

export function FetchStatus():Promise<api.IndexInfo>;

export function FetchStockMeta(arg1:string):Promise<api.StockMeta>;

export function InitBasicInfo():Promise<void>;
