// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['api']['App']['Connect'](arg1);
}

export function FetchStatus() {
  return window['go']['api']['App']['FetchStatus']();
}

export function FetchStockMeta(arg1) {
  return window['go']['api']['App']['FetchStockMeta'](arg1);
}

export function InitBasicInfo() {
  return window['go']['api']['App']['InitBasicInfo']();
}
